config/routes.rb
Rails.application.routes.draw do

  root 'shinlin#index'

  resources :products, :photos

  resource :session, only:[:create, :destroy]
  namespace :dashboard do
    namespace :sunjust do
      get 'sign_in' => "base#sign_in"
      resources :products, :photos, :posts
      resources :photos, except:[:index, :show]
      resources :posts, except:[:index, :show]
    end
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :image, PhotoUploader
  
  belongs_to :product

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :presence => {:message => "標題不能空白"}

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :photos, :inverse_of => :product, :dependent => :destroy

  accepts_nested_attributes_for :photos, allow_destroy: true

  validates :name, :presence => {:message => "產品名稱不得為空"}

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :user_signed_in?


  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    !!current_user
  end

  def authenticate_user!
    unless user_signed_in?
      redirect_to dashboard_sunjust_sign_in_path, notice:'請登入'
    end
  end
end

app/controllers/dashboard/dashboards_controller.rb
class Dashboard::DashboardsController < ApplicationController 

end

app/controllers/dashboard/sunjust/base_controller.rb
class Dashboard::Sunjust::BaseController < Dashboard::DashboardsController
  layout 'sl'

  before_action :authenticate_user!, except: [:sign_in]

  def sign_in

  end

end

app/controllers/dashboard/sunjust/photos_controller.rb
class Dashboard::Sunjust::PhotosController < Dashboard::Sunjust::BaseController
  before_action :set_photo, only: [:edit, :update, :destroy]
#
#  def edit
#  end
#  def update
#    if @photo.update(photo_params)
#      redirect_to edit_dashboard_sunjust_photo_path, notice: 'Photo image update'
#    end
#  end
#
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to edit_dashboard_sunjust_product_path(@photo.product.id)
  end


  private
  def set_photo 
    @photo = Photo.find(params[:id])
  end
#
#  def photo_params
#    params.require(:photo).permit(:image)
#  end
end

app/controllers/dashboard/sunjust/posts_controller.rb
class Dashboard::Sunjust::PostsController < Dashboard::Sunjust::BaseController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
    if @post.save

    format.html { redirect_to dashboard_sunjust_products_path, notice: '新增訊息成功'}
    format.json { render json: @post, status: :created, location: @post }
    else
      format.html {render :new}
      format.json { render json: @post.errors, status: :unprocessable_entity}
    end
    end
  #   redirect_to posts_path, notice: '新增產品成功'
  # else 
  #   render :new
  # end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to :back, notice: '成功修改資料'
    else
      render :edit, notice: '修改失敗'
    end
  end

  def destroy
    @post.destroy
    redirect_to dashboard_sunjust_products_path, notice:'訊息已刪除'

  end

  private
  def set_post
    @post = Post.find(params[:id])
  end 
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/dashboard/sunjust/products_controller.rb
class Dashboard::Sunjust::ProductsController < Dashboard::Sunjust::BaseController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.order(name: :asc)
    @posts = Post.order(created_at: :DESC)
  end

  def new
    @product = Product.new
    @photo = @product.photos.build
  end

  def create
    @product = Product.new(product_params)

  #  render text:params
   # return

    respond_to do |format|
    if @product.save
      if params[:images]
        params[:images].each { |image|
          @product.photos.create(image: image)
        }
      end

    format.html { redirect_to dashboard_sunjust_products_path, notice: '新增產品成功'}
    format.json { render json: @product, status: :created, location: @product }
    else
      format.html { render :new }
      format.json { render json: @product.errors, status: :unprocessable_entity}
    end
    end
  #   redirect_to products_path, notice: '新增產品成功'
  # else 
  #   render :new
  # end
  end

  def show
    @photos = @product.photos.all
  end

  def edit
  end

  def update
    if @product.update(product_params)
      if params[:images]
        params[:images].each { |image|
          @product.photos.create(image: image)
        }
      end
      redirect_to :back, notice: '成功修改資料'
    else
      render :edit, notice: '修改失敗'
    end
  end

  def destroy
    @product.destroy
    redirect_to dashboard_sunjust_products_path, notice:'產品已刪除'

  end

  private
  def set_product
    @product = Product.find(params[:id])
  end 

  def product_params
    params.require(:product).permit(:name, :en_name, :texture, :diameter, :size, :surface, photos_attributes: [:id, :images, :product_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all.page(params[:page]).per(18)
  end

  def show 
    @products = Product.all
    @product = Product.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
    user = User.find_by(name: params[:name])
    if user = user.try(:authenticate, params[:password])
      session[:user_id] = user.id
      redirect_to dashboard_sunjust_products_path, notice: "哈囉鑫林! #{user.name}"
    else
      redirect_to dashboard_sunjust_sign_in_path, notice: "登入失敗"
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path, notice: "辛苦了，再見"
  end
end

app/controllers/shinlin_controller.rb
class ShinlinController < ApplicationController

  def index
    @products = Product.order("rand()").limit(6)
    @post = Post.last
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def img_blank (product)
    if product.photos.empty?
      image_tag"default.jpg"
    end
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shinlin_helper.rb
module ShinlinHelper
end

app/views/application/_admin_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '鑫林日用品', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to '新增產品', new_dashboard_sunjust_product_path %></li>
        <li><%= link_to '發佈消息', new_dashboard_sunjust_post_path %></li>
        <li><%= link_to "hi, #{current_user.name}" %> </li>
        <li><%= link_to '登出', session_path, method: :delete %></li>
      </ul>
      <% end %>
    </div>
  </div>
</nav>
    

app/views/application/_admin_sidebar.html.erb
<div class="col-sm-3 col-md-2 sidebar">
  <ul class="nav nav-sidebar">
    <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
    <li><%= link_to '產品管理', dashboard_sunjust_products_path %></li>
    <li><%= link_to '消息管理', dashboard_sunjust_posts_path %></li>
  </ul>
</div>

app/views/application/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= message %>
  </div>
<% end %>

app/views/dashboard/sunjust/base/sign_in.html.erb
<% if user_signed_in? %>
  hello <%= current_user.name %> |
  <%= link_to "登出", session_path, method: :delete %>
<% else %>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <%= form_tag '/session', html: {class:"form-horizontal"} do %>
        <div class="form-group">
          <%= label_tag :name %>
          <%= text_field_tag :name, nil,class:'form-control' %>
        </div>
        <div class="form-group">
          <%= label_tag :password %>
          <%= password_field_tag :password,nil, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= submit_tag '登入', class: "btn btn-success" %>
        </div>  
      <% end %>
    </div>
  </div>
<% end %>

  

app/views/dashboard/sunjust/photos/_form.html.erb
<%= image_tag @photo.image %>
<%= form_for [:dashboard, :sunjust, @photo] do |f| %>
  <div>
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>
  <%= f.submit %>
<% end %>

app/views/dashboard/sunjust/photos/edit.html.erb
<%= render 'form' %>

app/views/dashboard/sunjust/posts/_form.html.erb
<%= simple_form_for [:dashboard, :sunjust, @post], wrapper: :horizontal_form do |f| %>
  <%= f.input :title, label:'標題', label_html: { class: 'col-sm-3'} %>

  <%= f.input :content, label:'內容', label_html: { class: 'col-sm-3'}, input_html: {:rows => "8"} %>
  <div class="col-sm-3 control-label">
    <%= f.button :submit, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/dashboard/sunjust/posts/edit.html.erb
<div class="row">
  <div class="col-sm-3">
    <h4 class="pull-right">編輯消息</h4>
  </div>
  <div class="col-sm-9">
    <h4>
      建立時間：<%= @post.created_at.strftime("%m/%d %H:%M %Y") %>
    </h4>
  </div>
</div>
<%= render 'form' %>

app/views/dashboard/sunjust/posts/new.html.erb
<div class="row">
  <div class="col-sm-3">
    <h4 class="pull-right">鑫林消息</h4>
  </div>
</div>
<%= render 'form' %>

app/views/dashboard/sunjust/products/_form.html.erb
<div class="col-sm-5 col-md-5 col-sm-offset-1" >
  <div class="row">
    <div class="col-sm-3">
      <h4 class="pull-right">產品資料</h4>
    </div>
  </div>
  <%= simple_form_for [:dashboard, :sunjust, @product], html: {multipart: true }, wrapper: :horizontal_form do |f| %>
    <%= f.input :name, label:'品名',label_html:{ class:'col-sm-3'}, input_html: {class:'col-sm-9'}, wrapper_html: {class:'row'} %>
    <%= f.input :en_name, label:'英文',label_html:{ class:'col-sm-3'}, input_html: {class:'col-sm-9'}, wrapper_html: {class:'row'} %>
    <%= f.input :texture, label:'材質',label_html:{ class:'col-sm-3'}, input_html: {class:'col-sm-9'}, wrapper_html: {class:'row'} %>
    <%= f.input :diameter, label:'管徑',label_html:{ class:'col-sm-3'}, input_html: {class:'col-sm-9'}, wrapper_html: {class:'row'} %>
    <%= f.input :size, label:'尺寸',label_html:{ class:'col-sm-3'}, input_html: {class:'col-sm-9'}, wrapper_html: {class:'row'} %>
    <%= f.input :surface, label:'表面',label_html:{ class:'col-sm-3'}, input_html: {class:'col-sm-9'}, wrapper_html: {class:'row'} %>
    <%= f.input :photos, :as => :file, label:'照片',label_html:{ class:'col-sm-3'}, input_html: {:multiple => true, class:'col-sm-9', :name => "images[]"}, wrapper_html: {class:'row'} %>
    <div class="col-sm-3 control-label">
      <%= f.button :submit, class:'btn-success' %>
    </div>
  <% end %>

</div>

app/views/dashboard/sunjust/products/_post.html.erb
<div class="col-sm-12 col-md-5">
  <h2 class="sub-header">所有消息</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <td>標題</td>
        <td>時間</td>
        <td></td>
      </tr>
    <tbody>
        <% @posts.each do |post| %>
      <tr>
          <td>
            <%= link_to "#{post.title}", edit_dashboard_sunjust_post_path(post) %>
          </td>
          <td>
            <%= post.updated_at.strftime("%m/%d/%y") %>
          </td>
          <td>
            <%= link_to "刪除", dashboard_sunjust_post_path(post), method: :delete, class: 'btn btn-danger btn-sm', date: { confirm:'確定刪除?' } %>
          </td>
      </tr>
        <% end %>
    </tbody>
  </table>
</div>

app/views/dashboard/sunjust/products/edit.html.erb
<div class="row">
  <%= render 'form' %>
  <div class="col-sm-5 col-md-5">
      <h4>產品圖片</h4>
    <div class="row">
      <%= img_blank @product %>
      <% @product.photos.each do |photo| %>
        <div class="col-sm-6">
          <div class="img_thumb">
            <%= image_tag(photo.image.thumb) %>
            <%= link_to 'delete', dashboard_sunjust_photo_path(photo), method: :delete, class:"btn btn-sm btn-danger" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div> 

app/views/dashboard/sunjust/products/index.html.erb
<div class="">
  <div class="row">
    <div class="col-sm-12 col-md-5 col-md-offset-1">
      <h2 class="sub-header">所有產品</h2>
      <table class="table table-striped"> 
        <thead>
          <tr>
            <td width="90%">品名</td>
            <td></td>
          </tr>
        </thead>
        <tbody>
        <% @products.each do |product| %>
          <tr>
            <td>
              <%= link_to "#{product.name}", edit_dashboard_sunjust_product_path(product) %>
            </td>
            <td>
              <%= link_to "刪除", dashboard_sunjust_product_path(product), method: :delete, class: 'btn btn-danger btn-sm', date: { confirm:'確定刪除?' } %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <%= render 'post' %>
  </div>
</div>

app/views/dashboard/sunjust/products/new.html.erb
<div class="row">
  <%= render 'form' %>
  <div class="col-sm-5 col-md-5">
    <h4>沒有照片</h4>
  </div>
</div>

app/views/dashboard/sunjust/products/show.html.erb
<p><%= @product.name %></p>

<% @photos.each do |p| %>
  <%= image_tag p.image_url %>
  <%= link_to "Edit Photo", edit_dashboard_sunjust_photo_path(p) %>
<% end %>
<br>
<%= link_to 'Edit', edit_dashboard_sunjust_product_path(@product) %> |
<%= link_to 'Back', dashboard_sunjust_products_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shinlin</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag %>
  </head>
  <body>
    <%= yield %>
    <footer class="sl-footer">
      Copyright © Shin Lin Home Fashion All Rights Reserve.
    </footer>
  </body>
</html>

app/views/layouts/sl.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>鑫林日用品</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag %>
  </head>
  <body>
    <%= render 'application/admin_navbar' %>
    <div class="container-fluid" style="margin-top: 40px;">
      <div class="row">
        <%#= render 'application/admin_sidebar' %>
        <div class="col-sm-12 col-md-12 main">
          <%= render 'application/flash' %>
          <h1 class="page-header">
            <%= link_to '管理台', dashboard_sunjust_products_path %>
          </h1>
          <%= yield %>
        </div>
      </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/products/_header.html.erb
<nav class="navbar navbar-fixed-top">
  <div class="container product-header">
    <div class="row">
      <div class="col-sm-7">
        <%= link_to root_path do %>
          <%= image_tag("sl_logo_p.png", class:"img-responsive") %>
        <% end %>
      </div>
      <div class="col-sm-4 col-sm-offset-1 hidden-xs">
        <div class="header-contact pull-left">
          <span class="glyphicon glyphicon-info-sign pull-left" aria-hidden="true"></span>
          <p> 電 話 : 769-87735660</p>
          <p> 郵 箱 : sunjust02@163.com</p>
        <%#= image_tag("sl_contact_s.jpg", class:"img-responsive pull-left") %>
        </div>
      </div>
      <div class="col-sm-12 visible-xs">
         <p>歡迎聯擊 電話: 769-87735660 郵箱: sunjust01@163.com</p>
      </div>
    </div>
  </div>
</nav>

app/views/products/index.html.erb
<%= render 'products/header' %>
<div class="product-content">
  <div class="container">
    <div class="row">
      <% @products.each do |product| %>
      <div class="col-md-4">
        <div class="product-show">
          <%= link_to product_path(product) do %>
            <%= img_blank product %>
            <% product.photos.limit(1).each do |i| %>
              <%= image_tag(i.image, class:"product-image")%>
            <% end %>
            <h2><%= product.name %></h2>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
    <div>
      <%= paginate @products %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<%= render 'products/header' %>
<div class="product-content">
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <%= link_to products_path do %>
          <div class="product-list">
            產品列表
            <span class="glyphicon glyphicon-menu-right text-right" aria-hidden="true"></span>
          </div>
        <% end %>
        <div class="panel panel-product">
          <div class="list-group">
            <% @products.each do |product| %>
              <%= link_to "#{product.name}", product, class: 'list-group-item' %>
            <% end %>
            <%= link_to "鑫林首頁", root_path, class: "list-group-item" %>
          </div>
        </div>
      </div>

      <div class="col-sm-5 show-image">
        <%= img_blank @product %>
        <% @product.photos.each do |image| %> 
          <%= image_tag(image.image, class:'center-block') %>
        <% end %>
      </div>
      <div class="col-sm-4">
        <div class="product-detail ">
          <h2>
            <%= @product.name %><br/>
            <%= @product.en_name %>
          </h2>
          <table class="table product-table">
            <tr>
              <td>材質</td>
              <td><%= @product.texture %></td>
            </tr>
            <tr>
              <td>管徑</td>
              <td><%= @product.diameter %></td>
            </tr>
            <tr>
              <td>尺寸</td>
              <td><%= @product.size %></td>
            </tr>
            <tr>
              <td width="20%">加工</td>
              <td><%= @product.surface %></td>
            </tr>
          </table>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/shinlin/index.html.erb
<main class="sl-head">
  <div class="container, sl-index-bg">
    <h1>
      <span class="sl-icon">
        <%= link_to products_path do %>
          <div class="sl-tw pull-left">
            鑫林日用品
          </div>
          <div class="sl-en pull-left">
            Shin Lin
          </div>
        <% end %>
      </span>
    </h1>
  </div>
</main>
<div class="sl-content">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 sl-dashboard">
        <%= image_tag('sl_product.jpg') %>
        <div class="index-product sl-content-block">
          <div class="row">
            <% @products.each do |product| %>
              <div class="col-sm-6 col-md-4">
                <%= link_to product_path(product) do %>
                  <% product.photos.limit(1).each do |image| %>
                    <%= image_tag(image.image.thumb, class:"product-thumbnail") %>
                  <% end %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <%= link_to products_path do %>
          <div class="more-product">
            查看更多產品
          </div>
        <% end %>
      </div>
      <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 sl-dashboard">
        <%= image_tag('sl_logo.jpg') %>
        <div class="sl-content-block">
          <ul>主要供應產品
            <li>窗簾桿</li>
            <li>浴簾桿</li>
            <li>浴簾掛勾</li>
            <li>花架</li>
            <li>DIY 置物架</li>
          </ul>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 sl-dashboard">
        <%= image_tag('sl_contact.jpg') %>
        <div class="sl-content-block">
          <ul>歡迎聯繫我们
            <li>業 務 經 理  :  劉曉涵</li>
            <li>電 話   :  769-87735660</li>
            <li>傳 真   :  769-87735880</li>
            <li>郵 箱   :  sunjust02@163.com</li>
            <li>中國.廣東省東莞市清溪鎮</li>
            <li>三中金龍工業區蓮塘路6號</li>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="sl-about">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
        <h2>
          <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
          關於鑫林 
        </h2>
        <article>鑫林日用品有限公司是臺灣伸適企業有限公司於中國的延伸企業，臺灣成立於1988年，專門OEM生產世界知名品牌的浴簾杆，窗簾杆，門簾杆，花架，DIY傢俱及各類的伸縮杆類的產品，自行開發的產品也多成為市場上的主流，隨著公司不斷壯大及中國國內經濟快速成長，于2008年成立了鑫林日用品有限公司，占地面積11000平方米，三座車間，位處東莞市清溪鎮，臨近高速公路及鐵路，是生產五金廠品的重鎮，有得天獨厚的取材優勢。
        </article>
        <h2>
          <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
          加工能力
        </h2>
        <article>鑫林擁有三個車間，分別為五金加工部，烤漆加工部，包裝部，承接各種業務加工，並有強大的開發及生產能力，在窗簾杆，浴簾杆的日生產量可達六千套，烤漆加工產量一天更可達兩萬套，廠房有完整生產設備，如切管機，拋光機，磨管機，鉚釘機，彎管機，縮管機，衝床，滾拋機，送料機，卷料機......等精密機械，用於製造產品，以達到更高的生產效率，也備有多種品質測量儀器，如硬度測試計，鹽霧測試機，膜厚測試器，重量測試…等，來為品質做重重把關。
        </article>
        <h2>
          <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
          質量承諾
        </h2>
        <article>在董事長劉建聲先生的帶領下，將過去20多年生產的經驗及最優質的外銷產品引進了國內市場，讓國內消費者能以最經濟的消費就能享有與國際同步的高品質，高格調產品，多項專利產品加上多樣化的表面處理及強大的配件供應鏈，秉承著“客戶至上，品質為先，服務第一”的原則，我們竭誠為廣大新老客戶提供“充足的貨源、優良的品質以及完善的服務”。
        </article>
        <h2>
          <span class="glyphicon glyphicon-bullhorn" aria-hidden="true"></span>
          最新消息：<%= @post.title %>
        </h2>
        <artircle>
          <%= @post.content %>
        </article>


      </div>
    </div>
  </div> 
</div>